exports.weaponLists = array() = [
    'Kriss Vector' = {
        category: 'Primary',
        type: 'Sub Machine Gun',
        accuracy: 85,
        power: 30,
        range: 61,
        fire_rate: 78,
        stability: 88,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '96,000',
    },
    'KSG' = {
        category: 'Primary',
        type: 'Shotgun',
        accuracy: 55,
        power: 66,
        range: 42,
        fire_rate: 26,
        stability: 80,
        mobility: 95,
        ammunition: '6 / 18',
        shop: 'Gold',
        cost: '96,000'
    },
    'S1014' = {
        category: 'Primary',
        type: 'Shotgun',
        accuracy: 65,
        power: 42,
        range: 42,
        fire_rate: 32,
        stability: 88,
        mobility: 95,
        ammunition: '6 / 18',
        shop: 'Gold',
        cost: '96,000'
    },
    'ARX-160' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 89,
        power: 27,
        range: 61,
        fire_rate: 81,
        stability: 92,
        mobility: 83,
        ammunition: '35 / 105',
        shop: 'Gold',
        cost: '120,000'
    },
    'R5 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 87,
        power: 28,
        range: 61,
        fire_rate: 80,
        stability: 90,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '120,000'
    },
    'SCAR-L GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 85,
        power: 30,
        range: 61,
        fire_rate: 78,
        stability: 88,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '120,000'
    },
    'SIZ556XI CARBON' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 83,
        power: 31,
        range: 61,
        fire_rate: 76,
        stability: 87,
        mobility: 83,
        ammunition: '35 / 105',
        shop: 'Gold',
        cost: '120,000'
    },
    'EF88 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 81,
        power: 32,
        range: 61,
        fire_rate: 74,
        stability: 85,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '120,000'
    },
    'CZ 805 A2' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 80,
        power: 33,
        range: 61,
        fire_rate: 71,
        stability: 82,
        mobility: 83,
        ammunition: '35 / 105',
        shop: 'Gold',
        cost: '120,000'
    },
    'K2C GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 80,
        power: 34,
        range: 61,
        fire_rate: 70,
        stability: 81,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '120,000'
    },
    'G36 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 78,
        power: 35,
        range: 61,
        fire_rate: 68,
        stability: 78,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '120,000'
    },
    'HNK417 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 66,
        power: 45,
        range: 61,
        fire_rate: 54,
        stability: 43,
        mobility: 76,
        ammunition: '30 / 90',
        shop: 'Gold',
        cost: '120,000'
    },
    'TYPE95' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 65,
        power: 45,
        range: 61,
        fire_rate: 56,
        stability: 44,
        mobility: 76,
        ammunition: '35 / 105',
        shop: 'Gold',
        cost: '120,000'
    },
    'SCAR-H' = {
        category: 'Primary',
        type: 'Designated Marksman Rifle',
        accuracy: 90,
        power: 34,
        range: 87,
        fire_rate: 73,
        stability: 88,
        mobility: 76,
        ammunition: '20 / 80',
        shop: 'Gold',
        cost: '96,000'
    },
    'MK46' = {
        category: 'Primary',
        type: 'Light Machine Gun',
        accuracy: 64,
        power: 32,
        range: 78,
        fire_rate: 82,
        stability: 65,
        mobility: 76,
        ammunition: '100 / 200',
        shop: 'Gold',
        cost: '96,000'
    },
    'PECHENEG B' = {
        category: 'Primary',
        type: 'Light Machine Gun',
        accuracy: 58,
        power: 34,
        range: 78,
        fire_rate: 76,
        stability: 62,
        mobility: 76,
        ammunition: '100 / 200',
        shop: 'Gold',
        cost: '96,000'
    },
    'DRAGUNOV' = {
        category: 'Primary',
        type: 'Sniper Rifle',
        accuracy: 90,
        power: 88,
        range: 91,
        fire_rate: 20,
        stability: 40,
        mobility: 65,
        ammunition: '10 / 20',
        shop: 'Gold',
        cost: '192,000'
    },
    'MSR' = {
        category: 'Primary',
        type: 'Sniper Rifle',
        accuracy: 90,
        power: 88,
        range: 95,
        fire_rate: 15,
        stability: 40,
        mobility: 65,
        ammunition: '7 / 21',
        shop: 'Gold',
        cost: '192,000'
    },
    'BLAZER R93' = {
        category: 'Primary',
        type: 'Sniper Rifle',
        accuracy: 95,
        power: 98,
        range: 95,
        fire_rate: 13,
        stability: 22,
        mobility: 65,
        ammunition: '5 / 15',
        shop: 'Gold',
        cost: '192,000'
    },
    'SKORPION' = {
        category: 'Secondary',
        type: 'Machine Pistol',
        accuracy: 72,
        power: 19,
        range: 26,
        fire_rate: 80,
        stability: 78,
        mobility: 95,
        ammunition: '20 / 40',
        shop: 'Gold',
        cost: '72,000'
    },
    'M67 Frag Grenade' = {
        category: 'Grenade',
        type: 'Grenade',
        power: 100,
        mobility: 100,
        shop: 'Gold',
        cost: '3,500'
    },
    'M18 Smoke Grenade' = {
        category: 'Grenade',
        type: 'Grenade',
        mobility: 100,
        shop: 'Gold',
        cost: '5,000'
    },
    'MK13 FLASH' = {
        category: 'Grenade',
        type: 'Grenade',
        mobility: 100,
        shop: 'Gold',
        cost: '5,000'
    },
    'SIZMPX' = {
        category: 'Primary',
        type: 'Sub Machine Gun',
        accuracy: 84,
        power: 27,
        range: 26,
        fire_rate: 92,
        stability: 66,
        mobility: 95,
        ammunition: '35 / 105',
        shop: 'Medal',
        cost: '2,000'
    },
    'P90' = {
        category: 'Primary',
        type: 'Sub Machine Gun',
        accuracy: 86,
        power: 24,
        range: 30,
        fire_rate: 94,
        stability: 72,
        mobility: 88,
        ammunition: '50 / 100',
        shop: 'Medal',
        cost: '2,000'
    },
    'ACR GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 82,
        power: 32,
        range: 61,
        fire_rate: 75,
        stability: 86,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'MDR GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 82,
        power: 34,
        range: 61,
        fire_rate: 73,
        stability: 84,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'M4 CUSTOM GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 83,
        power: 35,
        range: 61,
        fire_rate: 72,
        stability: 85,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'S15 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 75,
        power: 37,
        range: 61,
        fire_rate:66 ,
        stability: 76,
        mobility: 83,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'SIZ556XI RUS GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 69,
        power: 46,
        range: 61,
        fire_rate: 58,
        stability: 56,
        mobility: 76,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'SR-47 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 66,
        power: 47,
        range: 61,
        fire_rate: 51,
        stability: 44,
        mobility: 76,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'AK12 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 64,
        power: 48,
        range: 61,
        fire_rate: 51,
        stability: 42,
        mobility: 76,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'AK47 GL' = {
        category: 'Primary',
        type: 'Assault Rifle',
        accuracy: 64,
        power: 48,
        range: 61,
        fire_rate: 51,
        stability: 42,
        mobility: 76,
        ammunition: '30 / 90',
        shop: 'Medal',
        cost: '2,500'
    },
    'MK14 MOD1' = {
        category: 'Primary',
        type: 'Designated Marksman Rifle',
        accuracy: 64,
        power: 49,
        range: 87,
        fire_rate: 56,
        stability: 40,
        mobility: 76,
        ammunition: '20 / 80',
        shop: 'Medal',
        cost: '2,500'
    },
    'AXMC' = {
        category: 'Primary',
        type: 'Sniper Rifle',
        accuracy: 96,
        power: 99,
        range: 96,
        fire_rate: 14,
        stability: 20,
        mobility: 65,
        ammunition: '5 / 15',
        shop: 'Medal',
        cost: '3,200'
    },
    'DSR-1' = {
        category: 'Primary',
        type: 'Sniper Rifle',
        accuracy: 96,
        power: 99,
        range: 96,
        fire_rate: 12,
        stability: 20,
        mobility: 65,
        ammunition: '5 / 15',
        shop: 'Medal',
        cost: '3,200'
    },
    'M107A1' = {
        category: 'Primary',
        type: 'Sniper Rifle',
        accuracy: 100,
        power: 100,
        range: 100,
        fire_rate: 8,
        stability: 10,
        mobility: 65,
        ammunition: '5 / 15',
        shop: 'Medal',
        cost: '3,200'
    },
    'MP7A1' = {
        category: 'Primary',
        type: 'Sub Machine Gun',
        accuracy: 69,
        power: 20,
        range: 26,
        fire_rate: 98,
        stability: 59,
        mobility: 95,
        ammunition: '40 / 120',
        shop: 'N/A',
        cost: 'N/A'
    },
    'HNK45C' = {
        category: 'Secondary',
        type: 'Pistol',
        accuracy: 95,
        power: 29,
        range: 26,
        fire_rate: 53,
        stability: 90,
        mobility: 95,
        ammunition: '15 / 30',
        shop: 'Medal',
        cost: '1,500'
    },
    'M45 CQBP' = {
        category: 'Secondary',
        type: 'Pistol',
        accuracy: 94,
        power: 35,
        range: 30,
        fire_rate: 50,
        stability: 88,
        mobility: 95,
        ammunition: '10 / 20',
        shop: 'Medal',
        cost: '1,500'
    },
    'DESERTEAGLE 50AE' = {
        category: 'Secondary',
        type: 'Pistol',
        accuracy: 90,
        power: 57,
        range: 42,
        fire_rate: 41,
        stability: 62,
        mobility: 95,
        ammunition: '6 / 18',
        shop: 'Medal',
        cost: '1,500'
    },
    'CAVALIERE RHINO' = {
        category: 'Secondary',
        type: 'Pistol',
        accuracy: 91,
        power: 59,
        range: 43,
        fire_rate: 43,
        stability: 64,
        mobility: 95,
        ammunition: '6 / 18',
        shop: 'Medal',
        cost: '1,500'
    },
    'G17 TIER1' = {
        category: 'Secondary',
        type: 'Pistol',
        accuracy: 98,
        power: 26,
        range: 26,
        fire_rate: 56,
        stability: 100,
        mobility: 95,
        ammunition: '15 / 45',
        shop: 'N/A',
        cost: 'N/A'
    },
    'KUKRI' = {
        category: 'Melee',
        type: 'Melee weapon',
        power: 100,
        range: 7,
        fire_rate: 20,
        mobility: 100,
        shop: 'Medal',
        cost: '1,500'
    },
    'TOMAHAWK' = {
        category: 'Melee',
        type: 'Melee weapon',
        power: 100,
        range: 7,
        fire_rate: 20,
        mobility: 100,
        shop: 'Medal',
        cost: '1,500'
    },
    'KARAMBIT' = {
        category: 'Melee',
        type: 'Melee weapon',
        power: 100,
        range: 5,
        fire_rate: 25,
        mobility: 100,
        shop: 'Medal',
        cost: '1,500'
    },
    'SEAL-PUP' = {
        category: 'Melee',
        type: 'Melee weapon',
        power: 100,
        range: 5,
        fire_rate: 25,
        mobility: 100,
        shop: 'Medal',
        cost: '1,500'
    },
    'NIMRAVUS' = {
        category: 'Melee',
        type: 'Melee weapon',
        power: 100,
        range: 5,
        fire_rate: 25,
        mobility: 100,
        shop: 'N/A',
        cost: 'N/A'
    },
];
